#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# postinst - things to do after installing the package
#

# File which tells LXDE which file extensions trigger what apps when double clicked
associations_file=/usr/share/applications/defaults.list
updated=0

# Video formats that kano-video-cli should handle
video_formats="
video/3gpp
video/3gpp2
video/annodex
video/dv
video/isivideo
video/mp2t
video/mp4
video/mpeg
video/ogg
video/quicktime
video/vivo
video/vnd.mpegurl
video/vnd.rn-realvideo
video/wavelet.xml
video/webm
video/anim
video/flic
video/flv
video/javafx
video/matroska
video/mng
video/ms-asf
video/ms-wmv
video/msvideo
video/nsv
video/ogm+ogg
video/sgi-movie
video/theora+ogg
video/quicktime
audio/x-wav
audio/mpeg
"

case "$1" in
    configure)
        # associate video files to kano-video-cli, so double click will watch them
        for v in $video_formats; do
            pattern="$v=video-cli.desktop"
            if [ `grep "$pattern" $associations_file | wc -l` -eq 0 ]; then
                echo "Registering video format: $pattern"
                echo "$pattern" >> $associations_file
                updated=1
            fi
        done

        if [ "$updated" == "1" ] && [ -x /usr/bin/update-mime-database ]; then
            /usr/bin/update-mime-database /usr/share/mime
        fi
        ;;

esac

#DEBHELPER#

exit 0
