#!/bin/bash

# postrm
#
# Copyright (C) 2015 Kano Computing Ltd.
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU GPL v2
#

case "$1" in
    remove|upgrade)

        # Restore the original Midori system wide settings
        rm -rf /etc/xdg/midori
        mv -f /etc/xdg/midori-original /etc/xdg/midori

        ;;
esac


#DEBHELPER#

exit 0
